Use the latest streamly master branch

diff --git a/.github/workflows/haskell.yml b/.github/workflows/haskell.yml
--- a/.github/workflows/haskell.yml
+++ b/.github/workflows/haskell.yml
@@ -27,6 +27,7 @@ jobs:
 
       BUILD: ${{ matrix.build }}
       GHCVER: ${{ matrix.ghc_version }}
+      CABALVER: ${{ matrix.cabal_version }}
       CABAL_BUILD_OPTIONS: ${{ matrix.cabal_build_options }}
       CABAL_PROJECT: ${{ matrix.cabal_project }}
       DISABLE_DOCS: ${{ matrix.disable_docs }}
@@ -36,15 +37,22 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        name: [8.10.4+macOS]
-        cabal_version: ["3.2"]
         include:
           - name: 8.10.4+macOS
             ghc_version: 8.10.4
             build: cabal-v2
             cabal_project: cabal.project
+            cabal_version: 3.2
             disable_docs: "y"
             cabal_build_options: "--flag interop"
+          - name: 9.2.4
+            ghc_version: 9.2.4
+            runner: ubuntu-latest
+            build: cabal
+            cabal_project: cabal.project
+            cabal_version: 3.6.2.0
+            disable_sdist_build: "y"
+            ignore_error: false
     steps:
     - uses: actions/checkout@v2
 
@@ -70,6 +78,32 @@ jobs:
         PACKCHECK_URL=${PACKCHECK_GITHUB_URL}/${PACKCHECK_GITHUB_COMMIT}/packcheck.sh
         if test ! -e "$PACKCHECK_LOCAL_PATH"; then $CURL -sL -o "$PACKCHECK_LOCAL_PATH" $PACKCHECK_URL; fi;
         chmod +x $PACKCHECK_LOCAL_PATH
+
+        os=$(uname -s -m)
+        case "$os" in
+          "Linux x86_64") GHCUP_ARCH="x86_64-linux" ;;
+          "Darwin x86_64") GHCUP_ARCH="x86_64-apple-darwin" ;;
+          *) echo "Unknown OS/Arch: $os"; exit 1;;
+        esac
+
+        # Check available versions here: https://downloads.haskell.org/~ghcup/
+        GHCUP_VER=0.1.18.0
+        $CURL -sL -o ./ghcup https://downloads.haskell.org/~ghcup/$GHCUP_VER/${GHCUP_ARCH}-ghcup-$GHCUP_VER
+        chmod +x ./ghcup
+        if test "$GHCVER" = "head"
+        then
+          # The URL may change, to find a working URL go to https://gitlab.haskell.org/ghc/ghc/-/jobs/
+          # Find a debian10 job, click on a passed/failed job, at the
+          # end of the output you will find the tar.xz name, put that after
+          # "raw/", and put the job name after "job=".
+          # Also see https://github.com/mpickering/ghc-artefact-nix/blob/master/gitlab-artifact.nix
+          ./ghcup install ghc -u https://gitlab.haskell.org/ghc/ghc/-/jobs/artifacts/master/raw/ghc-x86_64-linux-deb10-int_native-validate.tar.xz?job=x86_64-linux-deb10-int_native-validate head
+        else
+          ./ghcup install ghc $GHCVER
+        fi
+        ./ghcup install cabal $CABALVER
+        ./ghcup set ghc $GHCVER
+        ./ghcup set cabal $CABALVER
 
     - name: Run packcheck
       run: |
